### ISSUE TITLE
Pisces outputting 'Alignment error'

### ISSUE THREAD

**Issue by fmazzarotto** [Illumina/Pisces#59]
Hi,
I am experiencing the same issue as #32 (which I commented some days ago), which does not appear to be solved so I apologize if this is a duplicated post/issue. I am running the somatic workflow on exome sequencing data (GeminiMulti on the sorted bam (previously processed with GATK MarkDuplicates) -> samtools index new bam -> Pisces -> etc etc), but Pisces outputs this error:

`System.Exception: EOCPDX9-IDTp7UMI59-TTCGCCAT_S24_L004.PairRealigned.resorted.bam: Error processing chr 'chr12': Alignment error: Found change in direction without encountering stitched direction ---> Sys tem.IO.InvalidDataException: Alignment error: Found change in direction without encountering stitched direction at Pisces.Domain.Logic.CandidateVariantFinder.GetSupportDirection(CandidateAllele candidate, Read bamAlignment, Int32 startIndexInRead) at Pisces.Domain.Logic.CandidateVariantFinder.Create(AlleleCategory type, String chromosome, Int32 coordinate, String reference, String alternate, Read alignment, Int32 startIndexInRead, Int32 wellAnchoredAnchorSize) at Pisces.Domain.Logic.CandidateVariantFinder.ExtractInsertionFromOperation(Read alignment, String refChromosome, Int32 opStartIndexInRead, UInt32 operationLength, Int32 opStartIndexInReference, String chromosomeName) at Pisces.Domain.Logic.CandidateVariantFinder.ProcessCigarOps(Read alignment, String refChromosome, Int32 readStartPosition, String chromosomeName) at Pisces.Logic.SomaticVariantCaller.Execute() at Pisces.Processing.Logic.BaseGenomeProcessor.ProcessByBam(BamWorkRequest workRequest, String chrName) --- End of inner exception stack trace ---.`

I have tried several solutions, starting with the addition of the `--usestitchedxd true` option when running Pisces (advised in the discussion of #32 ), which did not change the result. I have also ran Gemini.dll specifically on chr12 several times to attempt and identify where the issue may arise from, but Gemini runs flawlessly with no errors irrespective of the options that I specify, while Pisces always ends up outputting this error.

I would be grateful for any help as I seem to be unable to fix this. Thanks very much.

**Comment by tamsen** [comment]
Hi, 

There is a new version out now you can try. Since I didn't deliberately fix this bug, I doubt its magically fixed but you can try..   https://github.com/tamsen/Pisces/releases/tag/v5.3.0.0

I'm afraid I'm swamped right now and wont have the time to really dig into this until late March (sorry!). In the meantime, this new more linux-friendly version on this fork should be much more friendly to debug on your own if you are comfortable trying. (build instructions and compiler suggestion here: https://github.com/tamsen/Pisces/blob/master/README.md , go to Build instructions section)

Or, if you can send me a bam and link to a public reference genome I can use it with, to reproduce the issue, I will try to trouble shoot as soon as I can get some free time. I dont think its a deep issue, probably just a matter of turning off a check that is no longer relevant.  Opening the issue on the new fork if you still see the issue in the new version, would also be helpful.

best
Tamsen

**Comment by fmazzarotto** [comment]
Hi Tamsen,
thanks very much for replying. I am currently using the more Linux-friendly version (v5.3.0.0) and I did not encounter any issue. I will link the reference genome version that I am using, and provide you with one of the bam files on which I was getting the error using the official version, if useful to you to fix this bug.
Best wishes

**Comment by tamsen** [comment]
oh that's great!

Since 5.3.0.0 does not show the bug, please don't worry about finding a bam to reproduce the issue in the old 5.2.10 version. I think its best to encourage everyone to move to the newer version.

best
Tamsen
